[colors.bright]
black = "0x414458"
blue = "0x7ab0df"
cyan = "0x50cad2"
green = "0x37d99e"
magenta = "0xc397d8"
red = "0xf87070"
white = "0xd4d5d5"
yellow = "0xffe59e"

[colors.normal]
black = "0x414458"
blue = "0x7ab0df"
cyan = "0x50cad2"
green = "0x37d99e"
magenta = "0xc397d8"
red = "0xf87070"
white = "0xd4d5d5"
yellow = "0xffe59e"

[colors.primary]
background = "0x000000"
# background = "0x101017"
foreground = "0xd4d5d5"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "~Alt"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window.dimensions]
columns = 85
lines = 21

[terminal.shell]
program = "tmux"

[window.padding]
x = 10
y = 5

[window]
opacity = 1.0
